EPMLABSBRN-868: BE: Change date formats to ISO format (into LocalDateTime)
Brain-up/brn pull request #2031
Opened 2021-06-23 14:04 UTC by nikolai4lazarev

EPMLABSBRN-868 https://jira.epam.com/jira/browse/EPMLABSBRN-868#

2021-06-23 16:08 UTC, koylubaevnt requested changes

2021-06-23 16:08 UTC, koylubaevnt commented on src/main/kotlin/com/epam/brn/config/gson/GsonConfiguration.kt
> +@Configuration
А не смотрел в сторону JavaTimeModule  для objectMapper у jackson?

врод для этого достаточно просто подключить зависимость:
compile "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.12.3"
а в aplpication.properties добавить:
spring.jackson.serialization.write-dates-as-timestamps=false

2021-07-04 14:12 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/ExerciseDto.kt
> +    var changedWhen: LocalDateTime? = null
lets stay with LocalDateTime and its initialization 
as Kotlin recommended to avoid ? every where we can.

LocalDateTime? -> LocalDateTime

2021-07-04 14:13 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/ExerciseWithTasksDto.kt
> +    var changedWhen: LocalDateTime? = null
same

2021-07-04 14:13 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/response/UserAccountDto.kt
> +    val changed: LocalDateTime? = null,
same

2021-07-04 14:13 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/response/UserWithAnalyticsDto.kt
> +    var lastDone: LocalDateTime? = null,
same

2021-07-04 14:14 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/model/UserAccount.kt
> +    var created: LocalDateTime? = null,
same 
LocalDateTime? -> LocalDateTime

2021-07-04 14:14 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/model/Exercise.kt
> +    var changedWhen: LocalDateTime? = null
same 
LocalDateTime? -> LocalDateTime

2021-07-04 14:15 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/model/UserAccount.kt
> +    var changed: LocalDateTime? = null,
same 
LocalDateTime? -> LocalDateTime

2021-07-04 14:17 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/service/ExerciseService.kt
> +        exercise.changedWhen = timeService.now()
we do not need to manage it manually now as we have AuditingEntityListener in Exercise model - this fields would be auto set

2021-07-04 14:18 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/service/YandexSpeechKitService.kt
> +    var iamTokenExpiresTime: LocalDateTime? = null
var iamTokenExpiresTime: LocalDateTime = LocalDateTime.now(ZoneOffset.UTC)

2021-07-04 14:19 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/service/YandexSpeechKitService.kt
> +        if (iamToken.isNotEmpty() && iamTokenExpiresTime != null && iamTokenExpiresTime!!.isAfter(timeService.now()))
please avoid 
!= null

2021-07-06 10:55 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/statistic/MonthStudyStatisticDto.kt
> +    val date: String,
why String?

2021-07-06 10:57 UTC, nikolai4lazarev commented on src/main/kotlin/com/epam/brn/dto/statistic/MonthStudyStatisticDto.kt
> +    val date: String,
Because it's easier to have any date format in the response if we use string

2021-07-06 11:08 UTC, ElenaSpb approved these changes

2021-07-06 11:35 UTC, merged