Design & implement rest api for delete subgroup
Brain-up/brn pull request #2041
Opened 2021-07-06 08:00 UTC by rkonoplev

[EPMLABSBRN-886](https://github.com/Brain-up/brn/issues/2034) 

**Description**:

delete end point only for subgroups without linked exercises yet

2021-07-06 09:21 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/controller/SubGroupController.kt
> +    @ApiOperation("Get subGroup for id.")
Get subGroup for id ->
Delete subGroup by id

2021-07-06 09:32 UTC, nikolai4lazarev commented on src/main/kotlin/com/epam/brn/service/SubGroupService.kt
> +            throw IllegalArgumentException("Impossible delete. SubGroup is not empty.")
The message is not really clear. Let's write something like "Can not delete subgroup because there are exercises that refer to the subgroup" for example

2021-07-06 09:35 UTC, nikolai4lazarev commented on src/main/kotlin/com/epam/brn/service/SubGroupService.kt
> +    fun deleteById(subGroupId: Long): Boolean {
Is there any reason to return a boolean value here? Because if we can not delete the subgroup, we throw an exception but do not return false. In another case, if we did not get the error then it means that we successfully deleted the subgroup, and there is no reason to return true. @ElenaSpb your thoughts?

2021-07-06 09:50 UTC, ElenaSpb requested changes
Also please add unit , integration tests,
and api description into raml.api

2021-07-06 09:50 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/service/SubGroupService.kt
> +    fun deleteById(subGroupId: Long): Boolean {
let it be void

2021-07-09 13:31 UTC, rkonoplev commented on src/main/kotlin/com/epam/brn/controller/SubGroupController.kt
> +    @ApiOperation("Get subGroup for id.")
Done

2021-07-09 13:32 UTC, rkonoplev commented on src/main/kotlin/com/epam/brn/service/SubGroupService.kt
> +            throw IllegalArgumentException("Impossible delete. SubGroup is not empty.")
Done

2021-07-09 17:42 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/service/SubGroupService.kt
> +        if (exerciseRepository.findExercisesBySubGroupId(subGroupId).isNotEmpty()) {
maybe it's better to make a query to db that will return just true/false, than to return a collection of exercises

2021-07-09 17:56 UTC, Dmitriy1Fokin commented
if the subgroup does not exist, 500 error is returned.  It may be better to add a presence check to the database. And if there is no subgroup do nothing

2021-07-09 17:58 UTC, Dmitriy1Fokin requested changes
if the subgroup does not exist, 500 error is returned. It may be better to add a presence check to the database. And if there is no subgroup do nothing

2021-07-16 11:17 UTC, Dmitriy1Fokin requested changes

2021-07-16 11:17 UTC, Dmitriy1Fokin commented on src/test/kotlin/com/epam/brn/service/SubGroupServiceTest.kt
> +        verify(exactly = 1) { exerciseRepository.findExercisesBySubGroupId(subGroupId) }
this test will fail. Please change findExercisesBySubGroupId to existsBySubGroupId

2021-07-19 11:58 UTC, Dmitriy1Fokin commented on api-contract/api.raml
> +        description: |
I think there is not enough indentation here

2021-07-19 11:58 UTC, Dmitriy1Fokin commented on api-contract/api.raml
> +              example: { "errors": "Can not delete subGroup because subGroup is not found by this id." }
I think the response will look like this:
{
    "data": [],
    "errors": ["Can not delete subGroup because subGroup is not found by this id."],
    "meta": []
}

2021-07-19 12:01 UTC, Dmitriy1Fokin commented on api-contract/api.raml
> +         body:
and here

2021-07-19 13:27 UTC, Dmitriy1Fokin approved these changes

2021-07-24 14:04 UTC, ElenaSpb commented on api-contract/api.raml
> +        204:
maybe better simpler 200 response?

2021-07-24 14:16 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/service/ExerciseGroupsService.kt
>      }
what the reason of this change?

2021-07-24 14:17 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/service/ExerciseGroupsService.kt
> +        return groups.map { group -> group.toDto() }
what the reason of this change?

2021-07-24 18:49 UTC, rkonoplev commented on src/main/kotlin/com/epam/brn/service/ExerciseGroupsService.kt
> +        return groups.map { group -> group.toDto() }
IDEA advised this change and Nikolay approved refactoring.

2021-07-24 18:52 UTC, rkonoplev commented on api-contract/api.raml
> +        204:
I’ve compared it earlier but the better solution is 204.

2021-07-25 13:57 UTC, ElenaSpb approved these changes

2021-07-25 13:57 UTC, ElenaSpb approved these changes

2021-07-25 14:15 UTC, merged