Feature/epmlabsbrn 884
Brain-up/brn pull request #2043
Opened 2021-07-08 09:14 UTC by KristevSM

[EPMLABSBRN-884](https://jira.epam.com/jira/browse/EPMLABSBRN-884)

- implemented REST API for adding new subgroup for existing series

2021-07-08 14:28 UTC, ElenaSpb approved these changes

2021-07-08 14:30 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/service/SubGroupService.kt
> +            throw IllegalArgumentException("The subgroup with name=${subGroupRequest.name} and the level=${subGroupRequest.level} already exists!")
we avoid {} in such cases

2021-07-08 19:25 UTC, KomlevDm approved these changes

2021-07-09 06:16 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/dto/request/SubGroupRequest.kt
> +class SubGroupRequest(
Can a class make a data class ? More suitable in semantics

2021-07-09 06:16 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/controller/AdminController.kt
> +        @Validated @RequestBody subGroupRequest: SubGroupRequest
Why do we use @Validated here when we can just use @Valid

2021-07-09 06:16 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/controller/AdminController.kt
> +        @RequestParam(value = "seriesId") seriesId: Long,
maybe add  @ApiParam for more information?

2021-07-09 07:52 UTC, nikolai4lazarev requested changes

2021-07-09 07:52 UTC, nikolai4lazarev commented on src/test/kotlin/com/epam/brn/integration/AdminControllerIT.kt
> +        result.map { it.id }.containsAll(
There are a lot of assertions for collections in kotest for this case. For example shouldContainAllInAnyOrder, shouldContainAll etc. Please, use one of those assertions. U can find more information in the kotest documentation

2021-07-09 10:51 UTC, KristevSM commented on src/main/kotlin/com/epam/brn/service/SubGroupService.kt
> +            throw IllegalArgumentException("The subgroup with name=${subGroupRequest.name} and the level=${subGroupRequest.level} already exists!")
done

2021-07-09 10:52 UTC, KristevSM commented on src/main/kotlin/com/epam/brn/dto/request/SubGroupRequest.kt
> +    var description: String?
done

2021-07-09 10:54 UTC, KristevSM commented on src/test/kotlin/com/epam/brn/integration/AdminControllerIT.kt
> +        result.map { it.id }.containsAll(
done

2021-07-09 12:58 UTC, KristevSM commented on src/main/kotlin/com/epam/brn/controller/AdminController.kt
> +        @RequestParam(value = "seriesId") seriesId: Long,
done

2021-07-09 12:58 UTC, KristevSM commented on src/main/kotlin/com/epam/brn/controller/AdminController.kt
> +        @Validated @RequestBody subGroupRequest: SubGroupRequest
done

2021-07-09 12:58 UTC, KristevSM commented on src/main/kotlin/com/epam/brn/dto/request/SubGroupRequest.kt
> +class SubGroupRequest(
done

2021-07-09 12:58 UTC, KristevSM commented on src/main/kotlin/com/epam/brn/dto/request/SubGroupRequest.kt
> +    @NotNull
done

2021-07-09 12:58 UTC, KristevSM commented on src/main/kotlin/com/epam/brn/dto/request/SubGroupRequest.kt
> +    @NotNull
done

2021-07-09 12:59 UTC, KristevSM commented on src/main/kotlin/com/epam/brn/dto/request/SubGroupRequest.kt
> +    @NotNull
done

2021-07-09 16:45 UTC, Dmitriy1Fokin approved these changes

2021-07-10 14:54 UTC, ElenaSpb approved these changes

2021-07-10 14:56 UTC, merged