Apply Kotlin validation in INPUT requests DTOs
Brain-up/brn pull request #2068
Opened 2021-08-05 16:22 UTC by rkonoplev

[EPMLABSBRN-891](https://github.com/Brain-up/brn/issues/2052)

**Description**:

use Kotlin validation in input request DTOs, refactor Java validation intro Kotlin by example

**Details**:

like in UserAccountCreateRequest: @field:NotEmpty

instead of simple @notblank as in Java(as it is not work in Kotlin)

2021-08-06 06:41 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/dto/HeadphonesDto.kt
> +    var name: String,
Are you sure you need to remove the default value?

2021-08-06 06:41 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/dto/SeriesDto.kt
> +    val group: Long,
I think it's better to leave the nullable for now. This is beyond the scope of the task

2021-08-06 06:41 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/dto/SeriesDto.kt
> -    @NotBlank
Why did I delete this?

2021-08-06 06:41 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/dto/SignalTaskDto.kt
> +    @field:JsonIgnore
there is no need to change here. This is not validation

2021-08-06 06:41 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/dto/WordsGroupSeriesTaskDto.kt
> +    @field:JsonIgnore
there is no need to change here. This is not validation

2021-08-06 06:41 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/dto/WordsSeriesTaskDto.kt
> +    @field:JsonIgnore
there is no need to change here. This is not validation

2021-08-06 06:41 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/dto/request/AudiometryHistoryRequest.kt
> +    @field: Nullable
And here it should definitely be @Nullable

2021-08-06 06:41 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/dto/request/ExerciseRequest.kt
> +    @get:JsonProperty("ids")
there is no need to change here. This is not validation

2021-08-06 06:41 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/dto/request/LoginDto.kt
> +    val email: String,
why did you write this field here?

2021-08-06 06:41 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/model/Series.kt
> +        group = exerciseGroup.id!!,
see the comment above in SeriesDto. kt

2021-08-06 10:03 UTC, rkonoplev commented on src/main/kotlin/com/epam/brn/dto/HeadphonesDto.kt
> +    var name: String,
This case was approver earlier.

2021-08-06 10:04 UTC, rkonoplev commented on src/main/kotlin/com/epam/brn/dto/SeriesDto.kt
> +    val group: Long,
This case was approver earlier.

2021-08-06 10:04 UTC, rkonoplev commented on src/main/kotlin/com/epam/brn/dto/SeriesDto.kt
> -    @NotBlank
This case was approver earlier.

2021-08-06 10:04 UTC, rkonoplev commented on src/main/kotlin/com/epam/brn/dto/request/LoginDto.kt
> +    val email: String,
This case was approver earlier.

2021-08-06 10:05 UTC, rkonoplev commented on src/main/kotlin/com/epam/brn/model/Series.kt
> +        group = exerciseGroup.id!!,
This case was approved earlier.

2021-08-11 05:40 UTC, Dmitriy1Fokin requested changes

2021-08-11 05:40 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/controller/AdminController.kt
> +    fun handleValidationExceptions(ex: MethodArgumentNotValidException): Map<String, String?>? {
why is it here? no need to add your debug code to the PR

2021-08-11 05:40 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/dto/SeriesDto.kt
> +    val group: Long,
return the nullable. We decided to make variables with an annotation @NotNull nullable

2021-08-11 05:40 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/dto/request/SubGroupRequest.kt
> +    @param:JsonProperty(value = "first-property", required = true)
these annotations are not needed here. return @field:NotBlank

2021-08-11 05:40 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/dto/request/SubGroupRequest.kt
> +    @param:JsonProperty(value = "second-property", required = true)
same

2021-08-11 05:40 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/dto/request/SubGroupRequest.kt
>      var level: Int,
Make field nullable

2021-08-11 05:40 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/dto/request/SubGroupRequest.kt
> +    @param:JsonProperty("third-property", required = true)
same

2021-08-11 05:40 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/dto/request/SubGroupRequest.kt
> +    @param:JsonProperty("fourth-property")
same

2021-08-11 05:40 UTC, Dmitriy1Fokin commented on src/test/kotlin/com/epam/brn/integration/AdminControllerIT.kt
> +    fun `when post request to subGroup and invalid name in subGroup then correct response`() {
these three tests can be combined into one. One endpoint one test

2021-08-11 05:40 UTC, Dmitriy1Fokin commented on src/main/kotlin/com/epam/brn/dto/request/UserAccountCreateRequest.kt
> +    @field:NotBlank(message = "{validation.field.fullName.empty}")
change message

2021-08-11 05:40 UTC, Dmitriy1Fokin commented on src/test/kotlin/com/epam/brn/integration/AdminControllerIT.kt
> +        val existedSeries = insertSeries()
any id is needed for the test. you don't need to create existedSeries

2021-08-11 05:40 UTC, Dmitriy1Fokin commented on src/test/kotlin/com/epam/brn/integration/AdminControllerIT.kt
> +            .andExpect(MockMvcResultMatchers.content().contentType(MediaType.APPLICATION_JSON))
you need to check the response body. It should contain the names of fields with errors

2021-08-11 05:40 UTC, Dmitriy1Fokin commented on src/test/kotlin/com/epam/brn/integration/AdminControllerIT.kt
> +    fun `when post request to subGroup and invalid code in subGroup then correct response`() {
the same comments as for the test above

2021-08-11 05:40 UTC, Dmitriy1Fokin commented on src/test/kotlin/com/epam/brn/integration/AdminControllerIT.kt
> +    fun `when post request to subGroup and invalid level in subGroup then correct response`() {
the same comments as for the test above

2021-08-11 08:26 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/SeriesDto.kt
> +    val group: Long,
as we discussed it should be Long? if it is used as request dto,
if only as a response - we can delete it

2021-08-11 08:28 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/StudyHistoryDto.kt
> +    @field:NotNull
same

2021-08-13 10:00 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/request/AudiometryHistoryRequest.kt
> +    var rightAnswers: Int,
@field:Nullable
var rightAnswers: Int,

->

   var rightAnswers: Int?=0,

2021-08-13 10:11 UTC, rkonoplev commented on src/main/kotlin/com/epam/brn/dto/request/AudiometryHistoryRequest.kt
> +    var rightAnswers: Int,
Resolved

2021-08-13 13:58 UTC, ElenaSpb approved these changes

2021-08-13 14:00 UTC, merged