2235 analytic fields
Brain-up/brn pull request #2237
Opened 2022-06-22 11:03 UTC by mironovandrei

PR for #2235 
Replace mocks for workDayByLastMonth, firstDone, and lastDone with real data

2022-06-24 15:41 UTC, koylubaevnt commented on src/main/kotlin/com/epam/brn/repo/StudyHistoryRepository.kt
> +    fun findFirstStartTimeByUserAccount(userId: Long?): LocalDateTime?
I think it is better to combine 2 sql into one. Like this
"SELECT MIN(s.startTime), MAX(s.startTime) FROM StudyHistory s WHERE user_id=:userId".
Because the fewer queries in the database the better.
For result you can use Spring Projection.

2022-06-25 14:02 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/response/UserWithAnalyticsResponse.kt
> +    var workDayByLastMonth: Int? = 0,
why fields are nullable type?

we always can fill them with values

2022-06-25 14:12 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/service/impl/UserAnalyticsServiceImpl.kt
> +            user.workDayByLastMonth = countWorkDaysForMonth(
lets rename it
workDayByLastMonth -> studyDaysInLastMonth
?

2022-06-25 14:14 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/service/impl/UserAnalyticsServiceImpl.kt
> +        val startOfLastMonth = now.minusMonths(1).withDayOfMonth(1).with(LocalTime.MIN)
I think it is extra params - 
we need first study day not in last month, but generally when user start study ,
same about endOfLastMonth
- we need last study day in whole period

2022-06-27 10:09 UTC, mironovandrei commented on src/main/kotlin/com/epam/brn/service/impl/UserAnalyticsServiceImpl.kt
> +        val startOfLastMonth = now.minusMonths(1).withDayOfMonth(1).with(LocalTime.MIN)
Sorry, can't fully understand what do you mean
For example: it's June now. It means that in workDayByLastMonth field we should have number of days in May, when user made something.
Is it my understanding wrong?

2022-06-27 15:59 UTC, mironovandrei commented on src/main/kotlin/com/epam/brn/dto/response/UserWithAnalyticsResponse.kt
> +    var workDayByLastMonth: Int? = 0,
Yes, you are right
It shouldn't be nullable
fixed

2022-06-27 16:00 UTC, mironovandrei commented on src/main/kotlin/com/epam/brn/service/impl/UserAnalyticsServiceImpl.kt
> +            user.workDayByLastMonth = countWorkDaysForMonth(
renamed

2022-06-28 05:48 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/repo/FirstLastVisitView.kt
> +interface FirstLastVisitView {
semantically it looks like FirstLastStudyView
?

2022-06-28 05:49 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/repo/FirstLastVisitView.kt
> +    val firstVisit: LocalDateTime?
firstStudyDate ?

2022-06-28 05:49 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/repo/FirstLastVisitView.kt
> +    val lastVisit: LocalDateTime?
lastStudyDate ?

2022-06-28 08:17 UTC, mironovandrei commented on src/main/kotlin/com/epam/brn/repo/FirstLastVisitView.kt
> +interface FirstLastVisitView {
yes
fixed

2022-06-28 08:17 UTC, mironovandrei commented on src/main/kotlin/com/epam/brn/repo/FirstLastVisitView.kt
> +    val firstVisit: LocalDateTime?
renamed

2022-06-28 15:57 UTC, koylubaevnt requested changes

2022-06-28 15:57 UTC, koylubaevnt commented on src/main/kotlin/com/epam/brn/repo/FirstLastStudyView.kt
> +interface FirstLastStudyView {
It is better to move this interface into model/projection folder. Need create projection folder in exists model folder.

2022-06-28 17:55 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/response/UserWithAnalyticsResponse.kt
> +    var firstDone: LocalDateTime? = null,
var firstDone: LocalDateTime? = null, // generally first done exercise

2022-06-28 17:55 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/response/UserWithAnalyticsResponse.kt
> +    var lastDone: LocalDateTime? = null,
var lastDone: LocalDateTime? = null, // generally last done exercise

2022-06-28 17:55 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/service/impl/UserAnalyticsServiceImpl.kt
> +        val startOfLastMonth = now.minusMonths(1).withDayOfMonth(1).with(LocalTime.MIN)
we need this data to this task 
https://github.com/Brain-up/brn/issues/2233
for this form 
![image](https://user-images.githubusercontent.com/15213856/176250170-950bd6be-0bce-41da-893f-ab40a58ccc65.png)

yes , it is not about last month - it is about general first/last visit

2022-06-29 08:27 UTC, mironovandrei commented on src/main/kotlin/com/epam/brn/service/impl/UserAnalyticsServiceImpl.kt
> +        val startOfLastMonth = now.minusMonths(1).withDayOfMonth(1).with(LocalTime.MIN)
My question was not about fields "first visit" and "last visit".
Please see [here](https://github.com/Brain-up/brn/blob/b04edcacf450c04167c74dbda62e2309c87f117b/src/main/kotlin/com/epam/brn/service/impl/UserAnalyticsServiceImpl.kt#L50).
The only place where we use variables "startOfLastMonth" and "endOfLastMonth" is function to count "studyDaysInLastMonth". 
For getting of first visit date and last visit date we have dedicated query to database(see [here](https://github.com/Brain-up/brn/blob/b04edcacf450c04167c74dbda62e2309c87f117b/src/main/kotlin/com/epam/brn/repo/StudyHistoryRepository.kt#L85).
I'll add comments for these fields to avoid such uncertainties in the future.

2022-06-29 08:48 UTC, mironovandrei commented on src/main/kotlin/com/epam/brn/dto/response/UserWithAnalyticsResponse.kt
> +    var lastDone: LocalDateTime? = null,
Yes
added comment to avoid any uncertainties

2022-06-29 08:48 UTC, mironovandrei commented on src/main/kotlin/com/epam/brn/dto/response/UserWithAnalyticsResponse.kt
> +    var firstDone: LocalDateTime? = null,
Yes
added comment to avoid any uncertainties

2022-06-29 09:02 UTC, koylubaevnt approved these changes

2022-06-30 09:05 UTC, ElenaSpb approved these changes

2022-07-01 09:10 UTC, lifeart approved these changes

2022-07-02 19:24 UTC, lifeart approved these changes

2022-07-02 19:24 UTC, merged