EPMLABSBRN-1123 Add "Spent time" and "Done exercises" columns
Brain-up/brn pull request #2260
Opened 2022-08-01 12:40 UTC by Mikleprog

Add "Spent time" and "Done exercises" columns, add *ngIf conditions

2022-08-01 17:29 UTC, koylubaevnt requested changes
In file user.model.ts (src/app/modules/admin/models) need add new properties too.
export interface User:
1. "Spent time"
2. "Done exercises"

2022-08-01 19:44 UTC, marklekin commented on frontend-angular/src/assets/i18n/en.json
> +              "DoneExercises": "Done exercises"
Recommended to use 'Done' instead 'Done exercises'.
1) It's long and space is limited (if other colums have to be added...)
2) If only 1 in the column, it looks ugly to use plural 'exerciseS'.
+3) 'Exercises Done' would sound better (I don't know the translated version)
@ElenaSpb, @alextanlan please take a look, thanks!

2022-08-02 09:21 UTC, Mikleprog commented on frontend-angular/src/assets/i18n/en.json
> +              "DoneExercises": "Done exercises"
"Done exercises"  and "Spent time" will be displayed on two lines so an additional word doesn't  consume much space  and header looks pretty good even on a small screen. If new columns be added probably better to add Scroll.
![image](https://user-images.githubusercontent.com/62326146/182340245-97401e38-70a5-4821-a593-6424a0e5bd82.png)

2022-08-02 09:44 UTC, marklekin approved these changes

2022-08-02 10:00 UTC, ElenaSpb approved these changes

2022-08-02 10:21 UTC, merged