[WIP] 2272 user daily statistic table ember
Brain-up/brn pull request #2274
Opened 2022-08-11 18:57 UTC by koylubaevnt

[EPMLABSBRN-XX](https://jira.epam.com/jira/browse/EPMLABSBRN-XX)

**Description**:

2022-08-11 19:21 UTC, lifeart commented on frontend/app/components/statistics/bar-chart/component.ts
> +  @tracked selectedIndex?: number | null;
looks like this prop is not used

2022-08-11 19:26 UTC, lifeart approved these changes

2022-08-17 05:13 UTC, koylubaevnt commented
@lifeart recheck please PR. I made some fixes...

2022-08-17 09:19 UTC, koylubaevnt commented on frontend/app/components/statistics/bar-chart/component.ts
> +  @tracked selectedIndex?: number | null;
Yes. I removed it.

2022-08-17 09:26 UTC, lifeart requested changes
removing approval as requested

2022-08-23 18:17 UTC, lifeart approved these changes

2022-08-24 05:49 UTC, merged