Added contributor model, repo, service, dto, controller
Brain-up/brn pull request #2287
Opened 2022-08-19 13:41 UTC by koylubaevnt

[EPMLABSBRN-XX](https://jira.epam.com/jira/browse/EPMLABSBRN-XX)

**Description**:

2022-08-19 13:57 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/ContributorAdminDto.kt
> +data class ContributorAdminDto(
not clear what you mean by Admin

if by use case to add/edit - so it should be
dto/request/ContributorRequest

2022-08-19 13:58 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/ContributorUserDto.kt
> +data class ContributorUserDto(
we are waiting as I understand
ContributorDevelopersResponse
and
ContributorSpesialistsResponse

2022-08-19 14:00 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/GitHubUserDto.kt
> +data class GitHubUserDto(
so let it be like in enum
ContributorDeveloperResponse
ContributorSpecialistResponse

2022-08-19 14:01 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/model/Contributor.kt
> +    var contribution: Long? = null,
Long?
->
Long = 0,

2022-08-19 14:03 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/service/ContributorServer.kt
> +interface ContributorServer {
ContributorServer 
->
ContributorService

2022-08-19 14:04 UTC, ElenaSpb requested changes
fix naming please

2022-08-19 17:12 UTC, koylubaevnt commented on src/main/kotlin/com/epam/brn/dto/ContributorUserDto.kt
> +data class ContributorUserDto(
Should we split Developers and Specialist? I think we can use both as one entity.
Different for ContributorUserDto and ContributorAdminDto: they are response, but one for user page and other for admin page...
I don't know how it's well name

2022-08-19 17:13 UTC, koylubaevnt commented on src/main/kotlin/com/epam/brn/dto/ContributorAdminDto.kt
> +data class ContributorAdminDto(
It's response for admin page. I don't know how it's well name

2022-08-19 17:20 UTC, koylubaevnt commented on src/main/kotlin/com/epam/brn/dto/GitHubUserDto.kt
> +data class GitHubUserDto(
I don't understand what does you mean?
GitHubUserDto its dto for information about github users. I think it's good for admin page to show information about it

2022-08-19 19:33 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/ContributorAdminDto.kt
> +data class ContributorAdminDto(
yes, I see, 
ContributorDetailsResponse ?
ContributorDetailsRequest for edit/add end-point later
?

2022-08-19 19:37 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/GitHubUserDto.kt
> +data class GitHubUserDto(
oh, yes, so 
dto/request/GitHubUserRequest
?

2022-08-19 20:42 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/ContributorUserDto.kt
> +data class ContributorUserDto(
->
ContributorResponse
one model for both end-point as fields are mostly the same
?

2022-08-20 04:30 UTC, koylubaevnt commented on src/main/kotlin/com/epam/brn/dto/ContributorAdminDto.kt
> +data class ContributorAdminDto(
Need add "ContributorDetailsRequest for edit/add end-point later" in issue where describe admin operation for contributors

2022-08-20 08:12 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/response/ContributorDetailsResponse.kt
> +    var gitHubUser: GitHubUserResponse?,
if they are only part of Response and do use separatly - looks like it is really Dto.
?
ContactDto
GitHubUserDto

2022-08-20 08:15 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/response/GitHubUserResponse.kt
> +)
why all fields are nullable?
how id can be nullable if the object is saved in our DB?
maybe name is notnullable too?

if Contributor do not have link to githubuser- so 
contributor.githubuser=null
?

2022-08-20 12:33 UTC, koylubaevnt commented on src/main/kotlin/com/epam/brn/dto/response/ContributorDetailsResponse.kt
> +    var gitHubUser: GitHubUserResponse?,
If they DTO then need move to dto folder?

2022-08-20 12:35 UTC, koylubaevnt commented on src/main/kotlin/com/epam/brn/dto/response/GitHubUserResponse.kt
> +)
Yes, If contrinutor don't have link to githubuser it was =null.
Id can't be null, I will fix it. I check field from github api, but think all field cant't be null. I will change it

2022-08-20 13:50 UTC, RudzMaksim approved these changes
Just a minor comment about REST URL.
I saw several other places in which I'm not sure but I need to learn the project and codebase before writing comments about them:)

2022-08-20 13:50 UTC, RudzMaksim commented on src/main/kotlin/com/epam/brn/controller/ContributorController.kt
> +@RequestMapping("/contributor")
As I can see by the code base, the plural form is used for REST URLs, so probably it should be '/contributors'

2022-08-20 14:33 UTC, ElenaSpb commented on src/main/kotlin/com/epam/brn/dto/response/ContributorDetailsResponse.kt
> +    var gitHubUser: GitHubUserResponse?,
yes

2022-08-20 17:57 UTC, ElenaSpb approved these changes

2022-08-20 17:59 UTC, merged